AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'dry-run-two

  Sample SAM Template for dryruntwo

  '
Globals:
  Function:
    Timeout: 3
Resources:
  dryrun:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-dev-pipeline-artifactsbucket-1n1y4cmehol2w/1007ba6f2fd6aed6daf87b6f392f298d
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
    Metadata:
      SamResourceId: dryrun
  Dryruntwoo:
    Type: AWS::Serverless::Function
    DeletionPolicy: Retain
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      AutoPublishAlias: dev
      Architectures:
      - x86_64
      Role: 'arn:aws:iam::128656805307:role/service-role/dryruntwoo-role-7w72g7oh'
Outputs:
  dryrun:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - dryrun
      - Arn
  dryrunIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - dryrunRole
      - Arn